In [3]:
import time
def fib(n):
    fibList=[1, 1]
    if n==1 or n==2:
        return 1
    for i in range(2,n):
        fibList.append( fibList[i-1] + fibList[i-2] )
    return fibList

start = time.time()
fibList = fib(9200)
print(fibList)
print(time.time()-start)

start = time.time()
fib = lambda n: 1 if n<=2 else fib(n-1) + fib(n-2)
fib(10)
print(time.time()-start)

start = time.time()
fib = lambda n, a=0, b=1 : a if n<=0 else fib(n-1,b, a+b)
fib(1200)
print(time.time()-start)

KeyboardInterrupt: 

In [ ]:
import time
def fib(P,n):
    fibList=[1, 1]
    if P==1 or P==2:
        return 1
    for i in range(2,P):
        fibList.append(fibList[i-1] + fibList[i-2])
        if n == fibList[i]:
            return i+1
    return -1

M = 10**13
P = 15*(10**12)
N = 10^1
# n_quo, n_rem = n // P, n % P
print(fib(P,N))

# start = time.time()
# fibList = fib(9200)
# print(time.time()-start)

In [ ]:
import time
from collections import deque

def fib(P,n):
    # dp1, dp2 = deque(), deque()
    # dp1.append(1)
    # dp2.append(1)
    fiblist = deque()
    fiblist.append(1)
    fiblist.append(1)
    for i in range(2,P):
        fiblist.append(fiblist[0]+fiblist[1])
        fiblist.popleft
        if n == fiblist[1]:
            return i+1
    return -1

M = 10**13
P = 15*(10**12)
N = 10^1
# n_quo, n_rem = n // P, n % P
print(fib(P,N))

# start = time.time()
# fibList = fib(9200)
# print(time.time()-start)

In [47]:
import time
from collections import deque

def getFibo(t1):
    n_modeM = N % M
    candidate = []
    a = 1
    b = 0
    c = a
    for i in range(1,t1+1):
        c = (a + b) % M
        a = b
        b = c
    if c == n_modeM:
        return True
    else:
        return False
    
def fibo_in_pesano(P,n):
    n_modeM = n % M
    candidate = []
    a = 1
    b = 0
    c = a
    for i in range(1,P): # (0 + [1~P])
        c = (a + b) % M
        a = b
        b = c
        if n_modeM == c:
            candidate.append(i)
    return candidate

k = 3
M = 10**k
P = 15*(10**(k-1))

N = 13

candidate = fibo_in_pesano(P,N)
print(candidate)
for i in candidate:
    for j in range(10):
        print(getFibo(i + j * P))
        # (getFibo(candidate + j * P) == n % M)


# n_quo, n_rem = n // P, n % P
print(fibo_in_pesano(P,N))

# start = time.time()
# fibList = fib(9200)
# print(time.time()-start)

[7, 1484, 1493]
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
[7, 1484, 1493]


K를 13에서 3까지 쪼개어 갈 때, 한단계 낮은 K의 피사노 주기에서는 같은 mod가 10개씩 반복적으로 들어있기 때문에 어느것의 위치가 상위 피사노 주기 인덱스기준 정답위치인지 판별 불가. 따라서 bottom-top으로 갈 때, 10개의 주기(m*10^(k-1): m=0:9) 의 각각의 인덱스에서 다음 K번째의 mod를 넣어보는 작업으로 정답의 후보인지 아닌지 재검출함.

https://hapby9921.tistory.com/entry/BOJ-13729-1013-%ED%94%BC%EB%B3%B4%EB%82%98%EC%B9%98

In [154]:
import sys
# sys.stdin = open("D:/test.txt", "r") 

def Mat_mul(A, B, M):
    C = [[0] * 2 for _ in range(2)]
    for i in range(2):
        for j in range(2):
            for k in range(2):
                C[i][j] += (A[i][k] * B[k][j])
                C[i][j] %= M
    return C

def Pesano(k):
    M, P = 10**k, 15*(10**(k-1))
    return M, P

def Fibo_gen(idx, M):
    mat_ans = [[1, 0], [0, 1]]
    mat_unit = [[1, 1], [1, 0]]

    while idx > 0:
        if idx & 1:
            mat_ans = Mat_mul(mat_ans, mat_unit, M)
        mat_unit = Mat_mul(mat_unit, mat_unit, M)
        idx >>= 1
    return mat_ans[1][0]

def Pesano_period(M,P,N):
    n_modeM = N % M
    a = 1
    b = 0
    c = a
    candidate = []
    for i in range(P): # (0 + [1~P])
        c = (a + b) % M
        a = b
        b = c
        if n_modeM == c:
            candidate.append(i+1) # put 0 in first idx
    return candidate

def solve(N):
    k = 3
    M,P = Pesano(k)
    candidate = Pesano_period(M,P,N) # minimum pesano(k=3) candidate
    M *= 10 # compare with next mod
    for k in range(3,13):
        temp = []
        for idx in candidate:
            for m in range(10):
                if Fibo_gen(idx + m*P, M)%M == N % M:
                    temp.append(idx + m*P)
        candidate = temp[:]
        M, P = M*10, P*10 # bottom-top
    # if len(candidate) == 0:
    #     ans = -1
    # else:
    #     ans = min(candidate)
    print(-1 if len(candidate) == 0 else min(candidate))

# N = int(sys.stdin.readline().strip())
N = 10^12+1
solve(N)

9366795780274


In [244]:
import sys

def Mat_mul(A, B, M):
    C = [[0] * 2 for _ in range(2)]
    for i in range(2):
        for j in range(2):
            for k in range(2):
                C[i][j] += (A[i][k] * B[k][j])
                C[i][j] %= M
    return C

def Pesano(k):
    M, P = 10**k, 15*(10**(k-1))
    return M, P

def Fibo_gen(idx, M):
    mat_ans = [[1, 0], [0, 1]]
    mat_unit = [[1, 1], [1, 0]]

    while idx > 0:
        if idx & 1:
            mat_ans = Mat_mul(mat_ans, mat_unit, M)
        mat_unit = Mat_mul(mat_unit, mat_unit, M)
        idx >>= 1
    return mat_ans[1][0]

def Pesano_period(M,P,N):
    n_modeM = N % M
    a, b, c = 1, 0, 1
    candidate = []
    if N == 0:
        candidate.append(0)
    elif N == 1:
        candidate.append(1)
    for i in range(2,P+1):
        c = (a + b) % M
        b = a
        a = c
        if n_modeM == c:
            candidate.append(i) # put 0 in first idx
    return candidate

def solve(N):
    k = 3
    M,P = Pesano(k)
    candidate = Pesano_period(M,P,N) # minimum pesano(k=3) candidate
    M *= 10 # compare with next mod
    for k in range(3,13):
        temp = []
        for idx in candidate:
            for m in range(10):
                if Fibo_gen(idx + m*P, M)%M == N % M:
                    temp.append(idx + m*P)
        candidate = temp[:]
        M, P = M*10, P*10 # bottom-top
    print(-1 if (len(candidate) == 0)|(N==10**13) else min(candidate))

N = int(input())
solve(N)

9366795780274


In [240]:
candidate = [9366795780274]
N = 7
print((7==10^13))
print(-1 if (len(candidate) == 0)|(N==10^13) else min(candidate))

True
-1


In [ ]:
from collections import deque

N = 1000000
A = [9,4,8,20,14,15,18]
Dp = deque()




In [55]:
from queue import PriorityQueue

Dp = PriorityQueue()
n = 7
numbers = [9,4,8,20,14,15,18]
ans = 0

for i in range(n):
    num = numbers[i] - i

    if (Dp[-1] > num) if not Dp.empty else 0:
        Dp.put(num)
        ans += Dp[-1] - num
        Dp.get()
        Dp.put(num)
    else:
        Dp.put(num)
    print(Dp)

print(ans)

0


In [33]:
from queue import PriorityQueue

Dp = PriorityQueue()
n = 7
numbers = [9,4,8,20,14,15,18]
ans = 0

for i in range(n):
    num = numbers[i]
    Dp.put(num)

print(Dp.get())


4


In [50]:
import heapq

heap = []
n = 7
numbers = [9,4,8,20,14,15,18]
ans = 0

for i in range(n):
    num = numbers[i]
    print(num)
    heapq.heappush(heap,num)
# heappop
print(heap[:])

# [9,4,8,20,14,15,18]
# [9] > [9 3] > [3] > [3 3]
# [3 3] > [6 3 3] 
# [6 3 3] > [17 6 3 3]
# [17 6 3 3] > [17 10 3 3 6] > [10 3 3 6] > [10 10 3 3 6]
# [10 10 3 3 6] > [10 10 10 3 3 6]
# [10 10 10 3 3 6] > [12 10 10 3 3 6 10]
# [12 10 10 3 3 6 10]

9
4
8
20
14
15
18
[4, 9, 8, 20, 14, 15, 18]


In [59]:
import heapq

heap = []
n = 7
numbers = [9,4,8,20,14,15,18]
ans = 0

for i in range(n):
    num = numbers[i] - i

    if (heap[0] > num) if len(heap) != 0 else 0:
        heapq.heappush(heap,num)
        ans += heap[0] - num
        heapq.heappop(heap)
        heapq.heappush(heap,num)
    else:
        heapq.heappush(heap,num)
    print(heap)

print(ans)

[9]
[3, 9]
[3, 9, 6]
[3, 9, 6, 17]
[3, 9, 6, 17, 10]
[3, 9, 6, 17, 10, 10]
[3, 9, 6, 17, 10, 10, 12]
0


In [87]:
import heapq

n = int(input())
A = list(map(int,input().split(' ')))
pq, ans = [], 0
for i in range(n):
    num = i - A[i]
    if pq and abs(pq[0]) > num:
        heapq.heappush(pq, num)
        ans += (num - pq[0])
        heapq.heappop(pq)
        heapq.heappush(pq, num)
    else:
        heapq.heappush(pq, num)
print(ans)

IndexError: list index out of range

In [143]:
import sys
import heapq

n = int(sys.stdin.readline().strip())
A = list(map(int,sys.stdin.readline().split()))
pq, ans = [], 0
for i in range(n):
    num = i - A[i]
    if pq and pq[0] < num:
        ans += (num - pq[0])
        heapq.heappush(pq, num)
        heapq.heappop(pq)
        heapq.heappush(pq, num)
    else:
        heapq.heappush(pq, num)
print(ans)

In [5]:
import sys
import heapq

A = [9,4,8,20,14,15,18]
A = [5,4,3,2,1]
n = len(A)

pq, ans = [], 0
for i in range(n):
    num = i - A[i]
    if pq and pq[0] < num:
        ans += (num - pq[0])
        heapq.heappush(pq, num)
        heapq.heappop(pq)
        heapq.heappush(pq, num)
    else:
        heapq.heappush(pq, num)
print(ans)

12


In [74]:
# [9,4,8,20,14,15,18]
# 1 [9] > [9 3] > [3] > [3 3]
# 2 [3 3] > [6 3 3] 
# 3 [6 3 3] > [17 6 3 3]
# 4 [17 6 3 3] > [17 10 3 3 6] > [10 3 3 6] > [10 10 3 3 6]
# 5 [10 10 3 3 6] > [10 10 10 3 3 6]
# 6 [10 10 10 3 3 6] > [12 10 10 3 3 6 10]
# 7 [12 10 10 3 3 6 10]

from queue import PriorityQueue

Dp = PriorityQueue()
n = 7
numbers = [9,4,8,20,14,15,18]
ans = 0
for i in range(n):
    numbers[i] = -(numbers[i] - i)


Dp.put(numbers[0])

Dp.put(numbers[1])
Dp.get()
Dp.put(numbers[1])

Dp.put(numbers[2])

Dp.put(numbers[3])

Dp.put(numbers[4])
Dp.get()
Dp.put(numbers[4])

In [ ]:
import sys; input = sys.stdin.readline

def bip_match(n, m): # 이분 매칭
    for nn, mm in [(n, m - 1), (n, m + 1), (n - 1, m - 1), (n - 1, m + 1), (n + 1, m - 1), (n + 1, m + 1)]: # 6방향으로 탐색
        if 0 <= nn < N and 0 <= mm < M and not visited[nn][mm] and seat[nn][mm]:
            visited[nn][mm] = True
            if connect[nn][mm] == [-1, -1] or bip_match(connect[nn][mm][0], connect[nn][mm][1]):
                connect[nn][mm] = [n, m]       
                return True
    return False

for _ in range(int(input())):
    N, M = map(int, input().split())
    matrix = [input().strip() for _ in range(N)]
    
    seat = [[False] * M for _ in range(N)] # 앉을 수 있는 자리인지 저장하기 위한 행렬
    answer = 0
    for n in range(N):
        for m in range(M):
            if matrix[n][m] == '.':
                seat[n][m] = True
                answer += 1 # 앉을 수 있는 자리이면 seat 갱신해주고 answer에 자리 수 저장
                
    connect = [[[-1] * 2 for _ in range(M)] for __ in range(N)] # 각 자리 별 연결 위치를 저장하는 행렬
    for n in range(N):
        for m in range(0, M, 2): # 여기서 짝수로 해도 되고 홀수로 해도 된다. 물론, 둘 다 하면 안된다.
            if seat[n][m]:
                visited = [[False] * M for _ in range(N)]
                if bip_match(n, m):
                    answer -= 1 # 이분 매칭이 될 때마다 앉을 수 있는 자리가 하나씩 줄어든다
                    
    print(answer)

In [95]:
# import numpy as np
# import matplotlib.pyplot as plt

def magic(n):
    if n % 2 == 1:
        # Odd order
        M = oddMagic(n)
    elif n % 4 == 0:
        # Doubly even order
        J = [(i % 4) // 2 for i in range(1, n + 1)]
        K = [[J[i] == J[j] for j in range(n)] for i in range(n)]
        M = [[i + 1 + j * n for j in range(n)] for i in range(n)]
        for i in range(n):
            for j in range(n):
                if K[i][j]:
                    M[i][j] = n * n + 1 - M[i][j]
    else:
        # Singly even order
        p = n // 2  # p is odd.
        M = oddMagic(p)
        M = [M[i] + [M[i][j] + 2 * p * p for j in range(p)] for i in range(p)]
        M += [[M[i][j] + 3 * p * p for j in range(p)] + [M[i][j] + p * p for j in range(p)] for i in range(p)]
        if n == 2:
            return M
        i = list(range(p))
        k = (n - 2) // 4
        j = list(range(k)) + list(range(n-k+1,n))
        i_p = i + [x+p for x in i]
        p_i = [x+p for x in i] + i
        for y in j:
            for x in range(n//2):
                M[i_p[x]][y], M[p_i[x]][y] = M[p_i[x]][y], M[i_p[x]][y]
        i = k
        j = [0] + [i]
        for y in j:
            M[i][y], M[i+p][y] = M[i+p][y], M[i][y]
    return M

def oddMagic(n):
    p = [i + 1 for i in range(n)]
    M = [[n * ((p[i] + p[j] - (n + 3) // 2) % n) + (p[i] + 2 * p[j] - 2) % n + 1 for j in range(n)] for i in range(n)]
    return M

N = int(input())
# temp = np.array(magic(N))
# plt.plot(list(temp.sum(axis=0)) + list(temp.sum(axis=1)) + [sum(np.diag(temp,k=0))] + [sum(np.diag(temp.transpose(),k=0))])
# plt.ylim([sum(np.diag(temp,k=0))-1, sum(np.diag(temp,k=0))+1])
for line in magic(N):
    print (' '.join(map(str, line)))

563 598 633 668 703 738 773 808 843 878 913 948 983 1018 1053 1088 1 36 71 106 141 176 211 246 281 316 351 386 421 456 491 526 561
597 632 667 702 737 772 807 842 877 912 947 982 1017 1052 1087 33 35 70 105 140 175 210 245 280 315 350 385 420 455 490 525 560 562
631 666 701 736 771 806 841 876 911 946 981 1016 1051 1086 32 34 69 104 139 174 209 244 279 314 349 384 419 454 489 524 559 594 596
665 700 735 770 805 840 875 910 945 980 1015 1050 1085 31 66 68 103 138 173 208 243 278 313 348 383 418 453 488 523 558 593 595 630
699 734 769 804 839 874 909 944 979 1014 1049 1084 30 65 67 102 137 172 207 242 277 312 347 382 417 452 487 522 557 592 627 629 664
733 768 803 838 873 908 943 978 1013 1048 1083 29 64 99 101 136 171 206 241 276 311 346 381 416 451 486 521 556 591 626 628 663 698
767 802 837 872 907 942 977 1012 1047 1082 28 63 98 100 135 170 205 240 275 310 345 380 415 450 485 520 555 590 625 660 662 697 732
801 836 871 906 941 976 1011 1046 1081 27 62 97 132 134 169 204 239 274 309 3